version: '3.8'

services:
  db:
    image: ankane/pgvector:latest
    container_name: maliki_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-maliki_ai}
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-mypassword}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
